# 사용자 정의 속성
profile:
  value: 'prod'
spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create # ddl 생성옵션 (개발초기에만 create, create-drop, 개발 update, 운영 none, validate)
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect